pubstompinfo/events/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, IntegerField, FormField, FieldList, DateTimeField, DecimalField, TextAreaField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import Required, Length, URL, Optional, ValidationError
from ..forms import AutocompleteField

from ..geo.models import Geoname
from ..leagues.models import League


def all_cities():
    return Geoname.get_cities().order_by(Geoname.country_code, Geoname.name)


def all_leagues():
    return League.query.order_by(League.name)


class VenueForm(Form):
    display_name = TextField("Name", validators=[Required(), Length(max=64)])
    address1 = TextField("Address 1", validators=[Required(), Length(max=64)])
    address2 = TextField("Address 2", validators=[Optional(), Length(max=64)])
    zip_code = TextField("Zip Code", validators=[Optional(), Length(max=64)])
    capacity = IntegerField("Capacity", validators=[Optional()])

    latitude = DecimalField("Latitude", places=8, validators=[Optional()])
    longitude = DecimalField("Longitude", places=8, validators=[Optional()])

    def __init__(self, csrf_enabled=False, *args, **kwargs):
        super(VenueForm, self).__init__(csrf_enabled=csrf_enabled, *args, **kwargs)


class DayForm(Form):
    start_time = DateTimeField("Opening date & time", validators=[Optional()])
    end_time = DateTimeField("Closing date & time", validators=[Optional()])

    def validate_end_time(self, field):
        if self.start_time.data > field.data:
            raise ValidationError('Closing time must be after opening time.')

    def validate_start_time(self, field):
        if self.end_time.data <= field.data:
            raise ValidationError('Opening time must be before closing time.')

    def __init__(self, csrf_enabled=False, *args, **kwargs):
        super(DayForm, self).__init__(csrf_enabled=csrf_enabled, *args, **kwargs)


class EventForm(Form):
    """ Form to edit an event """
    # Event model data
    league = QuerySelectField("League",
                              validators=[Required()],
                              description="Which league is this pubstomp gathering to watch?",
                              query_factory=all_leagues)

    # city = QuerySelectField("City",
    # validators=[Required()],
    #                         description="In which city is this pubstomp being held?",
    #                         query_factory=all_cities)

    city = AutocompleteField("City",
                             validators=[Required()],
                             description="In which city is this pubstomp being held?",
                             get_id="geonameid",
                             getter=lambda x: Geoname.get_cities().filter(Geoname.geonameid == x).first()
                             )

    name = TextField("Name", validators=[Required(), Length(max=64)])
    description = TextAreaField("Description", validators=[Optional()],
                                description="Enter some notes about your event. You can use Markdown for formatting here; <a href=\"https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet\" target=\"_blank\">cheatsheet</a>.")
    website = TextField("Website", validators=[Optional(), Length(max=128), URL()])

    venue = FormField(VenueForm)
    days = FieldList(FormField(DayForm), min_entries=1)

pubstompinfo/__init__.py
# New Relic agent
import newrelic.agent
newrelic.agent.initialize('newrelic.ini')

# Muh imports
from flask import Flask
from flask.ext.cache import Cache
from flask.ext.login import LoginManager
from flask.ext.openid import OpenID
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.markdown import Markdown
from raven.contrib.flask import Sentry
import steam
import os

# Create app
app = Flask(__name__,
            instance_relative_config=True,
            instance_path=os.path.join(os.path.abspath(os.path.dirname(__file__)), '../instance/'))

# Load default config
app.config.from_object("config")

# Load instance config
app.config.from_pyfile("config.py")

# Load extensions
mem_cache = Cache(app, config=app.config["CACHE_MEMCACHED"])
fs_cache = Cache(app, config=app.config["CACHE_FS"])
db = SQLAlchemy(app)
login_manager = LoginManager(app)
oid = OpenID(app)
markdown = Markdown(app, safe_mode="escape")
sentry = Sentry(app)

# Setup steamodd
steam.api.key.set(app.config['STEAM_API_KEY'])
steam.api.socket_timeout.set(5)

# Setup debugtoolbar if we're in debug mode.
if app.debug:
    from flask.ext.debugtoolbar import DebugToolbarExtension
    toolbar = DebugToolbarExtension(app)


# Set up jinja2 filters.
from .filters import escape_every_character,\
    timestamp_to_datestring,\
    datetime_to_datestring,\
    seconds_to_time,\
    number_format
app.add_template_filter(escape_every_character)
app.add_template_filter(timestamp_to_datestring)
app.add_template_filter(datetime_to_datestring)
app.add_template_filter(seconds_to_time)
app.add_template_filter(number_format)


# Load current app version into globals
from .helpers import current_version
app.config['VERSION'] = current_version()

# Load views
import views

# Load blueprints
from .users.views import mod as users_module
app.register_blueprint(users_module)

from .leagues.views import mod as leagues_module
app.register_blueprint(leagues_module)

from .geo.views import mod as geo_module
app.register_blueprint(geo_module)

from .events.views import mod as event_module
app.register_blueprint(event_module)

pubstompinfo/events/views.py
from flask import Blueprint, render_template, current_app, abort, flash, redirect, url_for
from flask_login import login_required, current_user
from .. import mem_cache, sentry, db
from models import Event, EventVenue, EventDay
from forms import EventForm
from datetime import datetime

mod = Blueprint("events", __name__, url_prefix="/events")


@mod.route("/")
@mod.route("/page/<int:page>/")
def events(page=1):
    _events = Event.query.\
        filter(Event.days.any(EventDay.end_time > datetime.now())).\
        paginate(page, current_app.config['EVENTS_PER_PAGE'])

    return render_template("events/events.html",
                           title="Events - {}".format(current_app.config['SITE_NAME']),
                           events=_events)


@mod.route("/<int:_id>/")
def event(_id):
    _event = Event.query.filter(Event.id == _id).first_or_404()
    return render_template("events/event.html",
                           title="{} - {}".format(_event.name, current_app.config['SITE_NAME']),
                           meta_description="A pubstomp for {} being held in {}. {}".format(
                               _event.league.name,
                               _event.city,
                               _event.short_description),
                           event=_event)


@mod.route('/create/', methods=["GET", "POST"])
@mod.route('/<int:_id>/edit/', methods=["GET", "POST"])
@login_required
def edit(_id=None):
    _event = Event.query.filter(Event.id == _id).first()
    if _event is not None:
        # Check if current user is an event organiser, if not they can't edit the event.
        if _event.can_edit(current_user) is False:
            abort(403)
    else:
        # We're making a new event
        _event = Event()
        _event.organisers.append(current_user)

    event_form = EventForm(obj=_event)

    if event_form.validate_on_submit():
        _event.league_id = event_form.league.data.id
        _event.city_id = event_form.city.data.geonameid
        _event.name = event_form.name.data
        _event.description = event_form.description.data
        _event.website = event_form.website.data
        db.session.add(_event)
        db.session.flush()

        # Venue
        venue = _event.venue
        if venue is None:
            venue = EventVenue()

        venue.event_id = _event.id
        venue.name = event_form.venue.display_name.data
        venue.address1 = event_form.venue.address1.data
        venue.address2 = event_form.venue.address2.data
        venue.zip_code = event_form.venue.zip_code.data
        venue.capacity = event_form.venue.capacity.data
        venue.latitude = event_form.venue.latitude.data
        venue.longitude = event_form.venue.longitude.data

        if venue.name:
            # Save the venue if it has a name
            db.session.add(venue)
        elif venue.id is not None:
            # It if doesn't have a name and it exists already, delete it's entry.
            db.session.delete(venue)

        # Delete all existing days
        for day in _event.days:
            db.session.delete(day)

        # Create new days from form data
        for _day in event_form.days:
            if _day.start_time.data and _day.end_time.data:
                day = EventDay(
                    _event.id,
                    _day.start_time.data,
                    _day.end_time.data,
                )
                db.session.add(day)

        db.session.commit()

        flash("Event saved", "success")
        return redirect(url_for("events.event", _id=_event.id))

    if _event.id is None:
        title = "Register event - {}".format(current_app.config['SITE_NAME'])
    else:
        title = "Edit {} - {}".format(_event.name, current_app.config['SITE_NAME'])

    return render_template("events/edit.html",
                           title=title,
                           form=event_form,
                           event=_event)

pubstompinfo/geo/views.py
from flask import Blueprint, render_template, current_app, abort, jsonify
from models import Geoname
from ..events.models import Event, EventDay
from .. import db

from datetime import datetime
import json

mod = Blueprint("geo", __name__, url_prefix="/geo")


@mod.route("/countries/")
@mod.route("/countries/page/<int:page>/")
def countries(page=1):
    _countries = Geoname.get_countries().paginate(page, current_app.config['COUNTRIES_PER_PAGE'])

    return render_template("geo/countries.html",
                           title="Countries - {}".format(current_app.config['SITE_NAME']),
                           countries=_countries)


@mod.route("/cities/")
@mod.route("/cities/page/<int:page>/")
def cities(page=1):
    _cities = Geoname.get_cities(). \
        join(Event). \
        filter(Event.days.any(EventDay.end_time > datetime.now())). \
        group_by(Geoname.geonameid). \
        order_by(db.func.count(Event.id).desc()
    ).paginate(page, current_app.config['CITIES_PER_PAGE'])

    # Get counts for this page of cities (fuck knows how to include it with the above call ^)
    counts = dict(db.session.query(Event.city_id, db.func.count(Event.id)).group_by(Event.city_id).filter(
        Event.city_id.in_([city.geonameid for city in _cities.items])).all())

    for item in _cities.items:
        item.events_count = counts.get(item.geonameid) or 0

    return render_template("geo/cities.html",
                           title="Cities - {}".format(current_app.config['SITE_NAME']),
                           cities=_cities)


@mod.route("/cities/<int:_id>")
def city(_id):
    _city = Geoname.query.filter(Geoname.geonameid == _id).first_or_404()

    return render_template("geo/city.html",
                           title=u"{} - {}".format(_city.name, current_app.config['SITE_NAME']),
                           meta_description=u"Dota 2 pubstomps happening in {}".format(_city),
                           city=_city)


@mod.route("/cities/autocomplete/<string:query>.json")
def city_autocomplete(query=None):
    if "," in query:
        query, delim, cc = query.partition(",")
        data = Geoname.city_autocomplete(query.strip(), cc=cc.strip())
    else:
        data = Geoname.city_autocomplete(query)

    return json.dumps([{
        "value": item.geonameid,
        "name": unicode(item)
    } for item in data])

pubstompinfo/leagues/views.py
from flask import Blueprint, render_template, current_app, abort
from .. import mem_cache, sentry, db
from models import League
from ..events.models import Event, EventDay
from datetime import datetime

mod = Blueprint("leagues", __name__, url_prefix="/leagues")


@mod.route("/")
@mod.route("/page/<int:page>/")
def leagues(page=1):
    _leagues = League.query.join(Event).\
        filter(Event.days.any(EventDay.end_time > datetime.now())).\
        paginate(page, current_app.config['LEAGUES_PER_PAGE'])
        # group_by(League.id).\
        # order_by(db.func.count(Event.id).desc()).\

    return render_template("leagues/leagues.html",
                           title="Leagues - {}".format(current_app.config['SITE_NAME']),
                           leagues=_leagues)


@mod.before_app_request
def update_leauges():
    _updated_key = 'league_info_updated'
    _lock_key = 'league_info_update_lock'

    # If the last-updated key has expired, and the lock is not set (the lock will be set if another request
    # beat this one to the job)
    if not mem_cache.get(_updated_key) and not mem_cache.get(_lock_key):
        # Set lock before doing expensive task.
        mem_cache.set(_lock_key, True, timeout=current_app.config['UPDATE_LEAGUES_TIMEOUT'])  # Timeout in case the app crashes before it releases the lock.

        # Update hero data
        League.update_leagues_from_webapi()

        # Set key to say we've updated the data.  We'll re-run this process when this key expires
        mem_cache.set(_updated_key, True, timeout=current_app.config['UPDATE_LEAGUES_TIMEOUT'])  # 1 hour timeout

        # Release the lock
        mem_cache.delete(_lock_key)


@mod.route("/<int:_id>/")
def league(_id):
    _league = League.query.filter(League.id == _id).first_or_404()
    return render_template("leagues/league.html",
                           title="{} - {}".format(_league.name, current_app.config['SITE_NAME']),
                           meta_description=u"Dota 2 pubstomps for {} across the world.".format(_league.name),
                           league=_league)

pubstompinfo/views.py
from flask import render_template, flash
from . import app, db
from flask.ext.login import current_user
from events.models import Event, EventDay
from geo.models import Geoname
from leagues.models import League
from datetime import datetime


# Routes
@app.route('/')
def index():
    """
    Pubstomp.info home page. TODO
    :return: Response
    """

    events = Event.query.filter(Event.days.any(EventDay.end_time > datetime.now()))
    new_events = events.order_by(Event.created_at).limit(8)

    popular_leagues = League.query.join(Event).\
        filter(Event.days.any(EventDay.end_time > datetime.now())).\
        limit(4). \
        all()

    popular_cities = Geoname.get_cities(). \
        join(Event). \
        filter(
            Event.days.any(EventDay.end_time > datetime.now())). \
            group_by(Geoname.geonameid). \
            order_by(db.func.count(Event.id).desc()
        ). \
        limit(8). \
        all()

    # Get counts for this page of cities (fuck knows how to include it with the above call ^)
    city_counts = dict(db.session.query(Event.city_id, db.func.count(Event.id)).group_by(Event.city_id).filter(
        Event.city_id.in_([city.geonameid for city in popular_cities])).all())

    for item in popular_cities:
        item.events_count = city_counts.get(item.geonameid) or 0

    return render_template("index.html",
                           events=events,
                           new_events=new_events,
                           popular_cities=popular_cities,
                           popular_leagues=popular_leagues)


@app.route('/about')
def about():
    return render_template("about.html",
                           title="About us")


@app.route('/contact')
def contact():
    return render_template("contact.html",
                           title="Contact us")


@app.route('/flash')
def _flash():
    flash("Abcdefghijklmnopqrstuvwxyz", "error")
    flash("Abcdefghijklmnopqrstuvwxyz", "notice")
    flash("Abcdefghijklmnopqrstuvwxyz", "success")

    return render_template("error.html", error=None)


@app.errorhandler(401)  # Unauthorized
@app.errorhandler(403)  # Forbidden
@app.errorhandler(404)  # > Missing middle!
@app.errorhandler(500)  # Internal server error.
# @app.errorhandler(Exception)  # Internal server error.
def internalerror(error):
    """ Custom error page, will catch 401, 403, 404, and 500, and output a friendly error message. """
    try:
        if error.code == 401:
            error.description = "I'm sorry Dave, I'm afraid I can't do that.  Try logging in."
        elif error.code == 403:
            if current_user.is_authenticated():
                error.description = "I'm sorry {}, I'm afraid I can't do that.  You do not have access to this resource.".format(current_user.name)
            else:
                # Shouldn't output 403 unless the user is logged in.
                error.description = "Hacker."
    except AttributeError:
        # Rollback the session
        db.session.rollback()

        # E500's don't populate the error object, so we do that here.
        error.code = 500
        error.name = "Internal Server Error"
        error.description = "Whoops! Something went wrong server-side.  Details of the problem has been sent to our developers for investigation."

    # Render the custom error page.
    return render_template("error.html", error=error, title=error.name), error.code

pubstompinfo/templates/about.html
{% extends "layout.html" %}

{% block content %}
    <section class="page-header">
        <h1>About us</h1>
    </section>
    <section class="about-us">
        <div class="about-pubstomp">
            <h2>Pubstomp.info</h2>

            <p>Pubstomp.info was created with two primary goals in mind: Make it easier for pubstomp organisers and
                pubstomp attendees to find out about eachother; and promote Dota 2 pubstomps in general year-round (i.e.
                not just focused on The International). The site is basically a directory of pubstomps which would-be
                attendees can browse to find events in their area; however we try to be distinct by making it super-easy
                to find events, and we try to ask event organisers all the right questions so attendees know exactly
                what to expect when they turn up at an event.</p>

            <p>The website is certainly not finished &ndash; we've got a lot of things on our TODO list, but it's
                functional and we think in a good-enough state for people to start using. The website is also completely
                open-source (<a href="{{ config['GITHUB_URL'] }}">code on GitHub</a>), so if you want to contribute
                you're more than welcome to.</p>

            <p>If you have any questions for the Pubstomp.info team, or if you have any feedback for us, feel free to
                e-mail us at <a href="mailto:{{ config['CONTACT_EMAIL']|escape_every_character|safe }}">
                    {{ config['CONTACT_EMAIL']|escape_every_character|safe }}</a>.
            </p>
        </div>

        <div class="about-arcana">
            <h2>Arcana.io</h2>

            <p>We are a small group of developers who like to build products and tools to help the communities around
                various Valve products. We've each been involved with Valve's products and their associated communities
                for many years, finding ways to contribute however we can. Arcana.io is our attempt at coalescing
                our skills to build some high-quality services for those communities (let us know how we're doing!).
                You can see some of our other projects on the footer below.</p>

            <p>If you're into stalking people, here's Christmas:</p>

            <table class="get-stalked">
                <tbody>
                <tr>
                    <th>Rob Jackson</th>
                    <td><a href="https://github.com/RJacksonm1">GitHub</a></td>
                    <td><a href="https://keybase.io/rjackson">KeyBase</a></td>
                    <td><a href="http://www.reddit.com/user/RJacksonm1">Reddit</a></td>
                    <td><a href="https://twitter.com/rjacksonm1">Twitter</a></td>
                    <td><a href="https://rjackson.me/">Website</a></td>
                </tr>
                <tr>
                    <th>Bence Nagy</th>
                    <td><a href="https://github.com/Underyx">GitHub</a></td>
                    <td><a href="https://keybase.io/underyx">KeyBase</a></td>
                    <td><a href="http://www.reddit.com/user/underyx">Reddit</a></td>
                    <td><a href="https://twitter.com/underyx">Twitter</a></td>
                    <td><a href="http://underyx.me/">Website</a></td>
                </tr>
                <tr>
                    <th>Ben Williams</th>
                    <td><a href="https://github.com/Smashman">GitHub</a></td>
                    <td><a href="https://keybase.io/smashman">KeyBase</a></td>
                    <td><a href="http://www.reddit.com/user/smashman2004">Reddit</a></td>
                    <td><a href="https://twitter.com/smashman2004">Twitter</a></td>
                    <td><a href="http://smash.mn/">Website</a></td>
                </tr>
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

pubstompinfo/templates/error.html
{% extends "layout.html" %}

{% block content %}
    <section>
        <div class="page-header">
            <h1>Error {{ error.code }} - {{ error.name }}</h1>
        </div>

        <p>
            {{ error.description }}
        </p>
    </section>
{% endblock %}

pubstompinfo/templates/index.html
{% extends "layout.html" %}
{% from "macros.html" import logo %}
{% from "leagues/macros.html" import league_card %}

{% block content %}
    <div class="hero">
        <div class="hero-inner">
            <a href="{{ url_for('index') }}" class="hero-logo">{{ logo() }}</a>

            <div class="hero-copy">
                <h1>Find nearby pubstomps!</h1>

                <p>Pubstomp.info is an event directory &ndash; intending to make it easier for would-be attendees to find
                    out about events going on near them.</p>

                <p>See if there's any on-going or upcoming events near you:</p>

                <div id="pubstomp-map" class="google-map" style="height: 500px;"></div>

                <a class="button" href="{{ url_for("events.edit") }}">Hosting an event?</a>
            </div>
        </div>
    </div>

    <section class="popular-leagues">
        <h2>Popular leagues</h2>

        <div class="cards">
            {% for league in popular_leagues %}
                {{ league_card(league) }}
            {% endfor %}
        </div>
    </section>

    <section class="home-page">
        <div class="new-events">
            <h2>New events</h2>
            <table>
                <thead>
                <tr>
                    <th>Name</th>
                    <th>City</th>
                    <th>League</th>
                </tr>
                </thead>
                <tbody>
                {% for new_event in new_events %}
                    <tr>
                        <td><a href="{{ url_for('events.event', _id=new_event.id) }}">{{ new_event.name }}</a></td>
                        <td><a href="{{ url_for('geo.city', _id=new_event.city.geonameid) }}">{{ new_event.city }}</a></td>
                        <td><a href="{{ url_for('leagues.league', _id=new_event.league.id) }}">{{ new_event.league.name }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


        <div class="popular-cities">
            <h2>Popular cities</h2>
            <table>
                <thead>
                <tr>
                    <th>City</th>
                    <th>Events</th>
                </tr>
                </thead>
                <tbody>
                {% for popular_city in popular_cities %}
                    <tr>
                        <td><a href="{{ url_for('geo.city', _id=popular_city.geonameid) }}">{{ popular_city }}</a></td>
                        <td>{{ popular_city.events_count }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </section>
    
    <section class="see-also">
        <h2>See also</h2>

        <p>To find other events to attend, or to register your own events to spread the word &ndash; check out these websites:</p>

        <table>
            <tbody>
            <tr>
                <th>Dota 2's Pubstomp micro-site</th>
                <td>The International's official pubstomp listing micro-site; list your TI4 pubstomps here and get exposure on the official Dota 2 site and blog posts.</td>
                <td><a class="button" href="http://www.dota2.com/pubstomps/?via-pubstomp-info">Visit</a></td>
            </tr>
            <tr>
                <th>Esport Meetings</th>
                <td>A community website for listing and finding e-sports events for a variety of popular e-sport games.</td>
                <td><a class="button" href="http://esportmeetings.net/?via-pubstomp-info">Visit</a></td>
            </tr>
            <tr>
                <th>/r/dota2pubstomps</th>
                <td>A subreddit for organising and finding Dota 2 pubstomps.</td>
                <td><a class="button" href="http://www.reddit.com/r/dota2pubstomps/?via-pubstomp-info">Visit</a></td>
            </tr>
            <!-- TODO: When pubstomp.gg goes live
            <tr>
                <th>Pubstomp.gg</th>
                <td></td>
                <td><a class="button" href="http://pubstomp.gg/?via-pubstomp-info">Visit</a></td>
            </tr>
            -->
            </tbody>
        </table>


        </div>
    </section>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript"
            src="//maps.googleapis.com/maps/api/js?key={{ config['GMAPS_API_KEY'] }}">
    </script>
    <script type="text/javascript">
        var map,
            markers = [],
            infowindows = [];

        function initialize() {
            var mapOptions = {
                zoom: 2,
                center: {lat: 40, lng: 0}  // Doesn't work without a center ;(
            };

            // Create map
            map = new google.maps.Map(document.getElementById("pubstomp-map"), mapOptions);

            // Event markers,
            var data = [
                    {% for event in events %}
                        {# Make sure to escape appropriately, else pretty beefy XSS opportunities. #}
                        {
                            "id": {{ event.id|int }},
                            "name": "{{ event.name|replace('"', '\\"') }}",
                            "link": "{{ url_for("events.event", _id=event.id) }}",

                            "lat": {{ event.venue.latitude|float or event.city.latitude|float }},
                            "long": {{ event.venue.longitude|float or event.city.longitude|float }},

                            "city": "{{ event.city|replace('"', '\\"') }}",
                            "city_id": {{ event.city.geonameid|int }},
                            "city_link": "{{ url_for('geo.city', _id=event.city.geonameid) }}",

                            "league": "{{ event.league.name|replace('"', '\\"') }}",
                            "league_id": {{ event.league.id|int }},
                            "league.link": "{{ url_for('leagues.league', _id=event.league.id) }}"
                        },
                    {% endfor %}
                ]; // TODO: Fetch data over AJAX, otherwise a BOATLOAD of xss potential.

            for (var i = 0; i < data.length; i++)
            {
                createMarker(data[i]);
            }

            fitToMarkers();
        }

        function createMarker(event)
        {
            var marker = new google.maps.Marker({
                    map: map,
                    title: event.name,
                    position: {
                        lat: event.lat,
                        lng: event.long
                    }
                });

            marker.infowindow = new google.maps.InfoWindow({
                    content: '<div>' +
                        '<dl>' +
                        '<dt>Event name</dt>' +
                        '<dd><a href="' + event.link + '">' + event.name + '</a></dd>' +
                        '<dt>City</dt>' +
                        '<dd><a href="' + event.city_link + '">' + event.city + '</a></dd>' +
                        '<dt>League</dt>' +
                        '<dd><a href="' + event.league_link + '">' + event.league + '</a></dd>' +
                        '</dl>' +
                        '</div>' +
                        '<a class="button" href="' + event.link + '">View event</a>'
                });

            markers.push(marker);

            google.maps.event.addListener(
                marker,
                'click',
                function(e){
                    // Hide all other info windows
                    for (var i = 0, infowindow; infowindow = (markers[i] ? markers[i].infowindow : undefined); ++i) {
                        infowindow.close();
                    }
                    marker.infowindow.open(map, marker);
                }
            );
        }

        function fitToMarkers()
        {
            // Auto-zoom map to fit markers/
            // Credit to Google's Polymer-project
            // https://github.com/PolymerLabs/google-map/blob/master/google-map.html#L536

            var latLngBounds = new google.maps.LatLngBounds();
            for (var i = 0, m; m = markers[i]; ++i) {
                latLngBounds.extend(new google.maps.LatLng(m.position.lat(), m.position.lng()));
            }

            // For one marker, don't alter zoom, just center it.
            if (markers.length > 1) {
                map.fitBounds(latLngBounds);
            }

            map.setCenter(latLngBounds.getCenter());
        }

        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
{% endblock %}

pubstompinfo/templates/site_nav.html
{% from "macros.html" import logo %}

<header class="navigation">
    <div class="menu-wrapper">
        <a href="{{ url_for('index') }}" class="logo">
            {{ logo() }}
        </a>

        <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>

        <div class="nav">
            <ul id="navigation-menu">
                <li class="nav-link"><a href="{{ url_for('leagues.leagues') }}">Leagues</a></li>
                <li class="nav-link"><a href="{{ url_for('geo.cities') }}">Cities</a></li>
{#                <li class="nav-link"><a href="{{ url_for('geo.countries') }}">Countries</a></li>#}
                <li class="nav-link"><a href="{{ url_for('events.events') }}">Events</a></li>


                {% if current_user.is_admin() %}
                    <li class="nav-link"><a href="{{ url_for('users.users') }}">Users</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="navigation-tools">
            {% if current_user.is_authenticated() %}
                <a href="{{ url_for('users.logout') }}" class="user-logout">Logout</a>
                <a href="{{ url_for('users.user', _id=current_user.get_id()) }}" class="user-profile">{{ current_user.name }}</a>
            {% else %}
                <a href="{{ url_for('users.login') }}" class="sign-up">Sign in with Steam</a>
            {% endif %}
        </div>
    </div>
</header>